# Generated by Django 4.2 on 2023-04-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('genres', models.CharField(max_length=300, verbose_name='genres')),
                ('character_name_and_cast', models.CharField(max_length=400, verbose_name='character name and cast')),
                ('overview', models.CharField(max_length=500, verbose_name='overview')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('tagline', models.CharField(max_length=300, verbose_name='tagline')),
                ('vote_average', models.FloatField(verbose_name='average vote')),
                ('vote_count', models.IntegerField(verbose_name='vote count')),
            ],
        ),
    ]
